allowBuilds:
  '@ffmpeg-installer/darwin-arm64': true
  esbuild: true
  ffmpeg-static: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - ffmpeg-static
  - '@ffmpeg-installer/darwin-arm64'
  - esbuild
