/**
 * Safe one-time correction for the 5 known limited-rollout rows.
 *
 * These rows were generated by run-short-cover-intro-limited-rollout.ts before
 * the rollout script was patched to pre-stamp experiment IDs. They were rendered
 * correctly with cover intro, but experimentId/experimentVariant stayed HOOK/HOOK_V2
 * because the == null guard in runShortVideo blocked the write.
 *
 * This script:
 *  1. Reads the exact content IDs from the rollout report.
 *  2. Confirms each row meets ALL of these criteria before touching it:
 *     - ID appears in the rollout report (not a broad WHERE clause)
 *     - thumbnailText is set (cover intro ran and wrote coverText)
 *     - videoPath points to an existing file on disk
 *     - experimentId is currently "HOOK" (not already corrected)
 *     - experimentVariant is currently "HOOK_V2"
 *  3. Only then updates experimentId → "short-cover-intro-v1"
 *                                  and experimentVariant → "intro_on_1p5s".
 *  4. Writes a correction report to:
 *     output/short-cover-intro-limited-rollout/tracking-correction-report.json
 *
 * Old HOOK/HOOK_V2 rows that are NOT in the rollout report are never touched.
 * Re-runnable: already-corrected rows are skipped (idempotent).
 */

import "dotenv/config";
import fs from "fs";
import path from "path";
import pg from "pg";

const { Pool } = pg;

const CWD         = process.cwd();
const REPORT_IN   = path.join(CWD, "output", "short-cover-intro-limited-rollout", "report.json");
const REPORT_OUT  = path.join(CWD, "output", "short-cover-intro-limited-rollout", "tracking-correction-report.json");

const EXPERIMENT_ID  = "short-cover-intro-v1";
const EXPERIMENT_VAR = "intro_on_1p5s";

type ReportItem = {
  contentId: string;
  topic: string | null;
  videoPath: string | null;
  thumbnailText: string | null;
  experimentId: string | null;
  experimentVariant: string | null;
  genResult: string;
  videoResult: string;
};

type DbRow = {
  id: string;
  topic: string | null;
  thumbnail_text: string | null;
  experiment_id: string | null;
  experiment_variant: string | null;
  video_path: string | null;
  video_status: string | null;
};

type CorrectionEntry = {
  contentId: string;
  topic: string | null;
  action: "corrected" | "skipped_already_correct" | "skipped_precondition_fail" | "not_found_in_db";
  skipReason?: string;
  before?: { experimentId: string | null; experimentVariant: string | null };
  after?: { experimentId: string; experimentVariant: string };
};

async function main() {
  // ── 1. Load rollout report ─────────────────────────────────────────────────
  if (!fs.existsSync(REPORT_IN)) {
    console.error(`[error] Rollout report not found: ${REPORT_IN}`);
    process.exit(1);
  }
  const report = JSON.parse(fs.readFileSync(REPORT_IN, "utf-8")) as { items: ReportItem[] };

  const rolloutItems = report.items.filter(
    (i) => i.genResult === "ok" && i.videoResult === "ok" && i.contentId.length === 36,
  );

  console.log(`\n═══════════════════════════════════════════════════════`);
  console.log(`  fix-short-cover-rollout-tracking`);
  console.log(`  Rollout items from report: ${rolloutItems.length}`);
  console.log(`═══════════════════════════════════════════════════════\n`);

  if (rolloutItems.length === 0) {
    console.error("[error] No valid rollout items found in report.");
    process.exit(1);
  }

  const rolloutIds = rolloutItems.map((i) => i.contentId);

  // ── 2. Load current DB state for those exact IDs ───────────────────────────
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });

  const { rows: dbRows } = await pool.query<DbRow>(
    `SELECT id, topic, thumbnail_text, experiment_id, experiment_variant, video_path, video_status
     FROM content_generations
     WHERE id = ANY($1)`,
    [rolloutIds],
  );

  const dbByid = new Map<string, DbRow>(dbRows.map((r) => [r.id, r]));

  // ── 3. Evaluate each rollout item ──────────────────────────────────────────
  const corrections: CorrectionEntry[] = [];
  const toUpdate: string[] = [];

  for (const item of rolloutItems) {
    const db = dbByid.get(item.contentId);

    if (!db) {
      corrections.push({ contentId: item.contentId, topic: item.topic, action: "not_found_in_db" });
      console.log(`  ⊘ ${item.contentId.slice(0, 8)} not found in DB`);
      continue;
    }

    // Already correct — idempotent skip
    if (db.experiment_id === EXPERIMENT_ID && db.experiment_variant === EXPERIMENT_VAR) {
      corrections.push({
        contentId: item.contentId, topic: db.topic, action: "skipped_already_correct",
        before: { experimentId: db.experiment_id, experimentVariant: db.experiment_variant },
      });
      console.log(`  ✓ ${item.contentId.slice(0, 8)} already correct — skip`);
      continue;
    }

    // Precondition checks
    const thumbOk   = !!db.thumbnail_text?.trim();
    const videoOk   = !!db.video_path && fs.existsSync(path.join(CWD, db.video_path));
    const expIdHook = db.experiment_id === "HOOK";
    const expVarHook = db.experiment_variant === "HOOK_V2";

    if (!thumbOk || !videoOk || !expIdHook || !expVarHook) {
      const reasons: string[] = [];
      if (!thumbOk)   reasons.push("thumbnailText_not_set");
      if (!videoOk)   reasons.push(`video_missing(${db.video_path ?? "null"})`);
      if (!expIdHook) reasons.push(`experimentId_not_HOOK(${db.experiment_id})`);
      if (!expVarHook) reasons.push(`experimentVariant_not_HOOK_V2(${db.experiment_variant})`);

      corrections.push({
        contentId: item.contentId, topic: db.topic,
        action: "skipped_precondition_fail",
        skipReason: reasons.join("; "),
        before: { experimentId: db.experiment_id, experimentVariant: db.experiment_variant },
      });
      console.log(`  ✗ ${item.contentId.slice(0, 8)} precondition fail: ${reasons.join("; ")}`);
      continue;
    }

    toUpdate.push(item.contentId);
    corrections.push({
      contentId: item.contentId, topic: db.topic,
      action: "corrected",
      before: { experimentId: db.experiment_id, experimentVariant: db.experiment_variant },
      after:  { experimentId: EXPERIMENT_ID, experimentVariant: EXPERIMENT_VAR },
    });
    console.log(`  ✏  ${item.contentId.slice(0, 8)} "${db.topic}" — will correct`);
  }

  // ── 4. Apply targeted update ───────────────────────────────────────────────
  let updatedCount = 0;
  if (toUpdate.length > 0) {
    console.log(`\n[update] Updating ${toUpdate.length} row(s)...`);
    const result = await pool.query(
      `UPDATE content_generations
       SET experiment_id = $1, experiment_variant = $2
       WHERE id = ANY($3)
         AND experiment_id = 'HOOK'
         AND experiment_variant = 'HOOK_V2'`,
      [EXPERIMENT_ID, EXPERIMENT_VAR, toUpdate],
    );
    updatedCount = result.rowCount ?? 0;
    console.log(`[update] Done — ${updatedCount} row(s) updated.`);
  }

  // ── 5. Verify ─────────────────────────────────────────────────────────────
  const { rows: verifyRows } = await pool.query<DbRow>(
    `SELECT id, topic, thumbnail_text, experiment_id, experiment_variant FROM content_generations WHERE id = ANY($1)`,
    [rolloutIds],
  );
  await pool.end();

  console.log("\n[verify] Final state:");
  let allPass = true;
  for (const r of verifyRows) {
    const pass = r.experiment_id === EXPERIMENT_ID && r.experiment_variant === EXPERIMENT_VAR && !!r.thumbnail_text?.trim();
    if (!pass) allPass = false;
    console.log(`  ${pass ? "✓" : "✗"} ${r.id.slice(0, 8)} expId="${r.experiment_id}" expVar="${r.experiment_variant}" thumb="${r.thumbnail_text}"`);
  }

  // ── 6. Write correction report ────────────────────────────────────────────
  const correctionReport = {
    correctedAt:   new Date().toISOString(),
    rolloutReport: REPORT_IN,
    summary: {
      rolloutItemsInReport: rolloutItems.length,
      corrected:            corrections.filter((c) => c.action === "corrected").length,
      alreadyCorrect:       corrections.filter((c) => c.action === "skipped_already_correct").length,
      preconditionFail:     corrections.filter((c) => c.action === "skipped_precondition_fail").length,
      notFoundInDb:         corrections.filter((c) => c.action === "not_found_in_db").length,
      dbRowsActuallyUpdated: updatedCount,
      allVerifyPass:        allPass,
    },
    corrections,
    verifyRows: verifyRows.map((r) => ({
      id: r.id,
      topic: r.topic,
      thumbnailText: r.thumbnail_text,
      experimentId: r.experiment_id,
      experimentVariant: r.experiment_variant,
    })),
    safety: {
      updateMethod:    "targeted by exact content IDs from rollout report",
      broadMutation:   false,
      oldRowsTouched:  false,
      whereClause:     "id = ANY([5 known IDs]) AND experiment_id = 'HOOK' AND experiment_variant = 'HOOK_V2'",
    },
  };

  fs.writeFileSync(REPORT_OUT, JSON.stringify(correctionReport, null, 2), "utf-8");
  console.log(`\n[report] ${REPORT_OUT}`);
  console.log(`═══ ${allPass ? "✓ CORRECTION COMPLETE" : "✗ SOME ITEMS FAILED VERIFY"} ═══\n`);

  if (!allPass) process.exit(1);
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
